version: "3.7"
services:
  php:
    build:
      args:
        user: mscc
        uid: 1000
      context: ./
      dockerfile: docker/php.dockerfile
    image: devcon2023-app
    container_name: devcon2023-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - devcon2023-net

  nginx:
    image: nginx:1.17-alpine
    container_name: devcon2023-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - devcon2023-net

networks:
  devcon2023-net:
    driver: bridge
